activated: true
license_key: Z0FBQUFBQnBGRUxrbUtsZ3Y2LWozbjFycnd4ejdfUHgxd2RIbjFWcEd6OVRlS093TlVxcTM4NDJLOG9RQklTWC1lS2lsdlIzbzY2aWN5REo0ZFBtRmtGcm9KUjd4SHk4RjBiT2YxbklGRnJrbTlrUzVhRjc5WHFHRHQ4clluVVRkX0l5eWl1YXJvaFVhWHhvMGFpYXhPa3VjR2F0VWtUcWNucnA5NmpYN0c4Y01LMHRmR3Z5SUNCUHZGOXROdElBM3NXbUFmQ2ZnUTlDSVQ5M1lnb01fa1VpdVNKeGl5SnJPQVdTWGtCdjd3d296SUNZUGdaa1V4SHFxR1o1M2hwNVFWSGFwN051YTQ2QUFKcGtYRkpOLUFGYVNuaG50SnRWZVBWVWpvd29OMDdBZU5tUXc1NWlMT3AzRVg3LXRfV1RLdlF1UzQxQjJrdFdJdzNKdmNLWWNCZUhDanFHWFlLdmRhS01oUGw3NzBDMUZKLVZCX1FRVDRjPQ==
activated_at: '2025-11-12T08:18:52.586949'
license_info:
  license_type: trial
  expiration_date: '2025-11-22T08:18:44.272748'
  days_remaining: 9
  deployment_id: deploy-20251112-K33J0GMX
